AWSTemplateFormatVersion: '2010-09-09'
Description: AWS Serverless Spring API - springbootawsserverless
Globals:
  Api:
    EndpointConfiguration: REGIONAL
Outputs:
  UppercaseApi:
    Description: URL for application
    Export:
      Name: UppercaseApi
    Value:
      Fn::Sub: https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/uppercase
Resources:
  UppercaseFunction:
    Properties:
      CodeUri: s3://run-main1-backend-sandbo-serverlessdeploymentbuck-1c7g34ntbyjlz/725dabd84b7b7d919096792c442a2300
      Events:
        GetResource:
          Properties:
            Method: any
            Path: /{proxy+}
          Type: Api
      Handler: org.smartinrubio.springbootawsserverless.StreamLambdaHandler::handleRequest
      MemorySize: 256
      Policies: AWSLambdaBasicExecutionRole
      Runtime: java8
      Timeout: 30
    Type: AWS::Serverless::Function
Transform: AWS::Serverless-2016-10-31
