AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Example Uppercase API written with SpringBoot with the aws-serverless-java-container library

Globals:
  Api:
    EndpointConfiguration: REGIONAL

Resources:
  UppercaseFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: com.amazonaws.serverless.sample.springboot.StreamLambdaHandler::handleRequest
      Runtime: java8
      CodeUri: target/spring-boot-aws-serverless-0.0.1-SNAPSHOT.jar
      MemorySize: 1512
      Policies: AWSLambdaBasicExecutionRole
      Timeout: 60
      Events:
        GetResource:
          Type: Api
          Properties:
            Path: /{proxy+}
            Method: any

Outputs:
  SpringBootUppercaseApi:
    Description: URL for application
    Value: !Sub 'https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/uppercase'
    Export:
      Name: SpringBootUppercaseApi